In [1]:
import pandas as pd
import numpy as np

In [8]:
Data = {
    'Age' : ['0-10', '11-20', '21-30', '31-40', '41-50', '0-10', '11-20', '21-30', '31-40', '41-50', '0-10', '11-20', '21-30', '31-40', '41-50'],
    'Salary' : [0,10000,200000,40000,50000,2500,12000,20000,4000,5000,500,1000,20000,4000,5000]
}

In [27]:
df = pd.DataFrame(Data)

In [10]:
df

      Age  Salary
0    0-10       0
1   11-20   10000
2   21-30  200000
3   31-40   40000
4   41-50   50000
5    0-10    2500
6   11-20   12000
7   21-30   20000
8   31-40    4000
9   41-50    5000
10   0-10     500
11  11-20    1000
12  21-30   20000
13  31-40    4000
14  41-50    5000

In [17]:
group = df.groupby('Age')['Salary']

In [18]:
group

In [23]:
summery = group.agg(['min', 'max', 'mean', 'std', 'median'])

In [24]:
print(summery)

         min     max          mean            std   median
Age
0-10       0    2500   1000.000000    1322.875656    500.0
11-20   1000   12000   7666.666667    5859.465277  10000.0
21-30  20000  200000  80000.000000  103923.048454  20000.0
31-40   4000   40000  16000.000000   20784.609691   4000.0
41-50   5000   50000  20000.000000   25980.762114   5000.0

In [26]:
df1 = pd.read_csv('Iris.csv')

In [28]:
Iris_group = df1.groupby('Species')

In [29]:
summery = Iris_group.agg(['min', 'max', 'mean', 'std', 'median'])

In [30]:
summery

                  Id                              SepalLengthCm              \
                 min  max   mean       std median           min  max   mean
Species
Iris-setosa        1   50   25.5  14.57738   25.5           4.3  5.8  5.006
Iris-versicolor   51  100   75.5  14.57738   75.5           4.9  7.0  5.936
Iris-virginica   101  150  125.5  14.57738  125.5           4.9  7.9  6.588

                                  ... PetalLengthCm                        \
                      std median  ...           min  max   mean       std
Species                           ...
Iris-setosa      0.352490    5.0  ...           1.0  1.9  1.464  0.173511
Iris-versicolor  0.516171    5.9  ...           3.0  5.1  4.260  0.469911
Iris-virginica   0.635880    6.5  ...           4.5  6.9  5.552  0.551895

                       PetalWidthCm
                median          min  max   mean       std median
Species
Iris-setosa       1.50          0.1  0.6  0.244  0.107210    0.2
Iris-versicolor   4.35          1.0  1.8  1.326  0.197753    1.3
Iris-virginica    5.55          1.4  2.5  2.026  0.274650    2.0

[3 rows x 25 columns]

In [32]:
for name, group1 in group:
    print(name)
    print(group1.agg(['min']))

0-10
min    0
Name: Salary, dtype: int64
11-20
min    1000
Name: Salary, dtype: int64
21-30
min    20000
Name: Salary, dtype: int64
31-40
min    4000
Name: Salary, dtype: int64
41-50
min    5000
Name: Salary, dtype: int64